name: Auth API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/autotrader-backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Grant execute permission for scripts
        run: |
          chmod +x gradlew
          chmod +x src/test/scripts/*.sh

      - name: Run unit and integration tests
        run: ./gradlew test

      - name: Run API tests
        run: |
          # Start the app in background
          nohup ./gradlew bootRun > /dev/null 2>&1 &
          # Wait for app to start
          sleep 30
          # Run newman tests
          newman run src/test/resources/postman/auth-collection.json -e src/test/resources/postman/test-env.json -r cli,htmlextra --reporter-htmlextra-export build/test-reports/newman
          # Kill the app
          pkill -f "java.*autotrader"

      - name: Upload test reports as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests
            build/test-reports
